services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234

  postgres:
    image: postgres:latest
    container_name: postgresdb
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234

volumes:
  mongo: {}
  postgres: {}