services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234

  postgres:
    image: postgres:latest
    container_name: postgresdb
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - '3307:3306'
    volumes:
      - mysql:/data
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: elasticsearch
    ports:
      - '9200:9200'
    environment:
      - node.name=elasticsearch
      - xpack.security.enabled=false
      - discovery.type=single-node

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=1234

volumes:
  mongo: {}
  postgres: {}
  mysql: {}