services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234

  postgres:
    image: postgres:latest
    container_name: postgresdb
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - '3307:3306'
    volumes:
      - mysql:/data
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234

  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      discovery.type: single-node

volumes:
  mongo: {}
  postgres: {}
  mysql: {}