server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://admin:1234@localhost:27017/companyservices?authSource=admin
  threads:
    virtual:
      enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/