server:
  port: 8083

spring:
  rabbitmq:
    host: localhost
    port: '5672'
    username: admin
    password: 1234
    queue: notification-queue
    exchange: notification-exchange
    routingKey: notification-key
  threads:
    virtual:
      enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/